[project]
name = "iai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.2.0",
    "python-dotenv>=1.0.1",
    "rich>=14.3.2",
]
